// Host test for the visionOS game-data validator and import transaction
// (visionos/GameData/GXGameDataValidator.*, GXGameDataInstall.*).
//
// Every fixture is a synthetic tree of tiny fabricated .big files with valid BIGF headers and
// fake content generated by this test. No retail Generals / Zero Hour data is used or shipped.
//
//   vision-gamedata-test                        run the full suite
//   vision-gamedata-test --validate ZH [BASE]   print the validator report for a real or fake
//                                               folder (read-only)
//   vision-gamedata-test --make-fixtures DIR    write the synthetic fixture trees used by the
//                                               simulator checks under DIR
#include <atomic>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <memory>
#include <set>
#include <sstream>
#include <string>
#include <vector>

#include "../../visionos/GameData/GXGameDataInstall.h"
#include "../../visionos/GameData/GXGameDataValidator.h"

#if !defined(_WIN32)
#include <unistd.h>
#endif

namespace fs = std::filesystem;
using namespace gxgd;

static int g_checks = 0;
static int g_failures = 0;

#define CHECK(cond, name)                                                                     \
    do {                                                                                      \
        g_checks++;                                                                           \
        if (!(cond)) {                                                                        \
            g_failures++;                                                                     \
            std::fprintf(stderr, "FAIL [%s:%d] %s\n", __FILE__, __LINE__, std::string(name).c_str()); \
        }                                                                                     \
    } while (0)

// ---------------------------------------------------------------------------------------
// Fixture builders
// ---------------------------------------------------------------------------------------

struct Entry {
    std::string path;
    uint32_t size = 1;  // payload bytes (content is fake: 0xA5)
};

static void PutBE(std::string& s, uint32_t v) {
    s.push_back(char(v >> 24));
    s.push_back(char(v >> 16));
    s.push_back(char(v >> 8));
    s.push_back(char(v));
}

// Writes a well-formed BIGF archive. Layout: 16-byte header, table, payloads.
static void WriteBig(const fs::path& file, const std::vector<Entry>& entries) {
    fs::create_directories(file.parent_path());
    uint32_t tableEnd = 16;
    for (const auto& e : entries) tableEnd += 8 + uint32_t(e.path.size()) + 1;
    uint32_t payload = 0;
    for (const auto& e : entries) payload += e.size;
    std::string out = "BIGF";
    // Retail total-size field is little endian and ignored by the loader.
    uint32_t total = tableEnd + payload;
    out.push_back(char(total));
    out.push_back(char(total >> 8));
    out.push_back(char(total >> 16));
    out.push_back(char(total >> 24));
    PutBE(out, uint32_t(entries.size()));
    PutBE(out, tableEnd);
    uint32_t off = tableEnd;
    for (const auto& e : entries) {
        PutBE(out, off);
        PutBE(out, e.size);
        out += e.path;
        out.push_back('\0');
        off += e.size;
    }
    for (const auto& e : entries) out.append(e.size, char(0xA5));
    std::ofstream f(file, std::ios::binary | std::ios::trunc);
    f.write(out.data(), std::streamsize(out.size()));
}

static void Archive(const fs::path& dir, const std::string& name, const std::string& entry = "sample") {
    WriteBig(dir / name, {{entry, 1}});
}

static void WriteFile(const fs::path& p, size_t bytes, char fill = 'x') {
    fs::create_directories(p.parent_path());
    std::ofstream f(p, std::ios::binary | std::ios::trunc);
    std::string chunk(65536, fill);
    while (bytes) {
        size_t n = std::min(bytes, chunk.size());
        f.write(chunk.data(), std::streamsize(n));
        bytes -= n;
    }
}

static void MakeBase(const fs::path& dir) {
    for (const char* n : kBaseArchives) {
        Archive(dir, n, std::string(n) == "INI.big" ? "Data\\INI\\Default\\Weather.ini" : "sample");
    }
}

static void MakeZh(const fs::path& dir) {
    for (const char* n : kZeroHourArchives) Archive(dir, n);
    Archive(dir, "EnglishZH.big", "Data\\English\\generals.csf");
}

static void MakeExtras(const fs::path& zh) {
    Archive(zh, "AudioEnglishZH.big", "Data\\Audio\\Speech\\x.wav");
    Archive(zh, "SpeechEnglishZH.big", "Data\\Audio\\Speech\\y.wav");
    WriteFile(zh / "Data" / "Movies" / "intro.bik", 3 * 1024 * 1024 + 123, 'v');
}

static fs::path MakeTemp(const char* tag) {
    std::string base = (fs::temp_directory_path() / (std::string("gxgd-") + tag + "-XXXXXX")).string();
    std::vector<char> buf(base.begin(), base.end());
    buf.push_back('\0');
    char* r = mkdtemp(buf.data());
    return fs::path(r ? r : base);
}

static std::map<std::string, uint64_t> TreeMap(const fs::path& root) {
    std::map<std::string, uint64_t> m;
    std::error_code ec;
    for (fs::recursive_directory_iterator it(root, ec), end; it != end; it.increment(ec)) {
        if (it->is_regular_file()) m[fs::relative(it->path(), root).generic_string()] = uint64_t(fs::file_size(it->path()));
    }
    return m;
}

static bool Contains(const std::vector<MissingItem>& v, const std::string& display) {
    for (const auto& m : v) {
        if (m.display() == display) return true;
    }
    return false;
}

// ---------------------------------------------------------------------------------------
// Engine BIGF reference: a line-by-line transcription of
// StdBIGFileSystem::openArchiveFile (Core/GameEngineDevice/Source/StdDevice/Common/
// StdBIGFileSystem.cpp), used to prove the validator's parser reads the same table.
// ---------------------------------------------------------------------------------------

struct EngineEntry {
    std::string path;
    int32_t offset;
    int32_t size;
};

static int32_t betoh32(int32_t v) {
    uint32_t u = uint32_t(v);
    return int32_t(((u & 0xFF) << 24) | ((u & 0xFF00) << 8) | ((u >> 8) & 0xFF00) | (u >> 24));
}

static bool EngineParse(const fs::path& file, std::vector<EngineEntry>& out) {
    FILE* fp = fopen(file.string().c_str(), "rb");
    if (!fp) return false;
    char buffer[260 + 1];
    if (fread(buffer, 1, 4, fp) != 4) { fclose(fp); return false; }
    buffer[4] = 0;
    if (strcmp(buffer, "BIGF") != 0) { fclose(fp); return false; }
    int32_t archiveFileSize = 0;
    if (fread(&archiveFileSize, 1, 4, fp) != 4) { fclose(fp); return false; }
    int32_t numLittleFiles = 0;
    if (fread(&numLittleFiles, 1, 4, fp) != 4) { fclose(fp); return false; }
    numLittleFiles = betoh32(numLittleFiles);
    fseek(fp, 0x10, SEEK_SET);
    for (int i = 0; i < numLittleFiles; ++i) {
        int32_t filesize = 0, fileOffset = 0;
        if (fread(&fileOffset, 1, 4, fp) != 4 || fread(&filesize, 1, 4, fp) != 4) { fclose(fp); return false; }
        filesize = betoh32(filesize);
        fileOffset = betoh32(fileOffset);
        int pathIndex = -1;
        do {
            ++pathIndex;
            if (fread(buffer + pathIndex, 1, 1, fp) != 1) { fclose(fp); return false; }
        } while (buffer[pathIndex] != 0);
        out.push_back({std::string(buffer), fileOffset, filesize});
    }
    fclose(fp);
    return true;
}

// ---------------------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------------------

static void TestConstants() {
    CHECK(sizeof(kBaseArchives) / sizeof(kBaseArchives[0]) == 10, "10 base archives");
    CHECK(sizeof(kZeroHourArchives) / sizeof(kZeroHourArchives[0]) == 10, "10 zh archives");
    CHECK(kMaxSearchDepth == 2 && kMaxFoldersVisited == 128, "search bounds");
    CHECK(std::string(kZeroHourArchives[0]) == "INIZH.big" && std::string(kBaseArchives[1]) == "Terrain.big", "markers");
}

static void TestValidatorPortOfAndroidSuite(const fs::path& temp) {
    // Steam nested base.
    fs::path steam = temp / "Steam" / "Zero Hour";
    MakeZh(steam);
    MakeBase(steam / "ZH_Generals");
    Report r = Validate(steam.string());
    CHECK(r.ready(), "Steam nested base ready");
    CHECK(r.baseLayout == BaseLayout::Nested, "Steam nested layout");
    CHECK(r.verdict() == Verdict::Ready, "Steam verdict ready");
    CHECK(r.baseRoot == (steam / "ZH_Generals").string(), "nested base path");
    CHECK(r.languages.size() == 1 && r.languages[0] == "English", "language English detected in archive");
    CHECK(r.weatherFound && r.languageFound, "weather+language inside archives");
    CHECK(r.baseSeparate() && r.totalBytesEstimate() > 0, "size estimate");

    // Retail patch with an empty placeholder entry at offset 0.
    WriteBig(steam / "PatchZH.big", {{"Data\\*", 0}});
    r = Validate(steam.string());
    CHECK(r.ready(), "Retail patch empty placeholder tolerated");
    bool patchWarn = false;
    for (const auto& w : r.warnings) patchWarn |= w.find("PatchZH.big") != std::string::npos;
    CHECK(patchWarn, "placeholder produces a warning, not an error");
    // The Java fixture patches the file with a hand-rolled table (offset 0 / size 0). Do the same.
    {
        std::fstream f(steam / "PatchZH.big", std::ios::in | std::ios::out | std::ios::binary);
        f.seekp(16);
        char zeros[8] = {0};
        f.write(zeros, 8);
    }
    CHECK(Validate(steam.string()).ready(), "Retail patch offset-0 placeholder tolerated (Java fixture)");

    CHECK(Validate(steam.parent_path().string()).ready(), "Steam parent folder selected");

    // Installed CD/ISO: sibling Zero Hour + Generals.
    fs::path retail = temp / "Retail" / "Zero Hour";
    fs::path retailBase = temp / "Retail" / "Generals";
    MakeZh(retail);
    MakeBase(retailBase);
    r = Validate(retail.string());
    CHECK(r.ready() && r.baseLayout == BaseLayout::Sibling, "CD/ISO installed sibling base");
    r = Validate(retail.string(), retailBase.string());
    CHECK(r.ready() && r.baseLayout == BaseLayout::Explicit, "Explicit split base");
    CHECK(!Validate(retailBase.string()).ready(), "Base-only rejected");
    CHECK(Validate(retailBase.string()).verdict() == Verdict::NoZeroHour, "Base-only verdict");

    // Merged install and case variants.
    fs::path merged = temp / "Merged";
    MakeZh(merged);
    MakeBase(merged);
    r = Validate(merged.string());
    CHECK(r.ready() && r.baseLayout == BaseLayout::Merged && r.baseRoot == r.zhRoot, "Merged install");
    CHECK(!r.baseSeparate(), "merged is not separate");
    fs::rename(merged / "Terrain.big", merged / "TERRAIN.BIG");
    CHECK(Validate(merged.string()).ready(), "Archive case variants");

    // Ambiguity.
    fs::path other = temp / "Steam" / "Another";
    MakeZh(other);
    r = Validate(steam.parent_path().string());
    CHECK(r.zhChoices.size() == 2, "Ambiguous installs");
    CHECK(r.verdict() == Verdict::Ambiguous && !r.ready(), "Ambiguous verdict");

    // Uninstalled disc.
    fs::path disc = temp / "Disc";
    fs::create_directories(disc);
    std::ofstream(disc / "data1.cab").put('x');
    r = Validate(disc.string());
    CHECK(r.installerDetected && r.verdict() == Verdict::InstallerOnly, "Uninstalled disc explanation");
    std::ofstream(temp / "game.iso").put('x');
    r = Validate((temp / "game.iso").string());
    CHECK(r.installerDetected && r.unreadable && r.verdict() == Verdict::InstallerOnly, "Raw .iso selection");

    // Missing ZH archive.
    fs::remove(merged / "MapsZH.big");
    r = Validate(merged.string());
    CHECK(!r.ready() && Contains(r.missing, "MapsZH.big"), "Missing ZH archive");
    CHECK(r.verdict() == Verdict::Incomplete, "Missing archive verdict incomplete");
    for (const auto& m : r.missing) {
        if (m.name == "MapsZH.big") CHECK(!m.reason.empty(), "missing item has a reason");
    }

    // Truncated payload with intact table.
    Archive(merged, "MapsZH.big");
    fs::resize_file(merged / "MapsZH.big", fs::file_size(merged / "MapsZH.big") - 1);
    r = Validate(merged.string());
    CHECK(r.damaged.size() == 1 && !r.ready(), "Truncated payload with intact table");
    CHECK(r.damaged[0].reason == "BIGF payload bounds", "truncated payload reason");

    // Malformed table count.
    Archive(merged, "MapsZH.big");
    {
        std::fstream f(merged / "MapsZH.big", std::ios::in | std::ios::out | std::ios::binary);
        f.seekp(8);
        char cnt[4] = {0, 0x0F, char(0x42), char(0x3F)};  // 999999 big endian
        f.write(cnt, 4);
    }
    CHECK(!Validate(merged.string()).ready(), "Malformed table count");

    CHECK(!Validate(steam.string(), (temp / "MissingBase").string()).ready(), "Explicit missing base never silently replaced");
    r = Validate(steam.string(), (temp / "MissingBase").string());
    CHECK(r.baseFolderMissing && r.baseRoot.empty(), "explicit missing base reported");
    CHECK(Validate(steam.string()).ready(), "Failed candidates never modify working files");

    // Base strings cannot replace expansion text.
    fs::path noText = temp / "NoText";
    MakeZh(noText);
    MakeBase(noText / "ZH_Generals");
    Archive(noText / "ZH_Generals", "English.big", "Data/English/generals.csf");
    fs::remove(noText / "EnglishZH.big");
    r = Validate(noText.string());
    CHECK(!r.ready() && !r.languageFound, "Base strings cannot replace expansion text");
    Archive(noText, "EnglishZH.big", "Data/English/generals.csf");
    fs::remove(noText / "AudioZH.big");
    CHECK(Contains(Validate(noText.string()).missing, "AudioZH.big"), "Missing expansion sound");

    // Missing base archive is prefixed like the Android list.
    fs::path noBaseArchive = temp / "NoBaseArchive";
    MakeZh(noBaseArchive);
    MakeBase(noBaseArchive / "ZH_Generals");
    fs::remove(noBaseArchive / "ZH_Generals" / "Maps.big");
    r = Validate(noBaseArchive.string());
    CHECK(Contains(r.missing, "Generals: Maps.big") && !r.ready(), "Missing base archive is prefixed 'Generals: '");
    CHECK(!r.baseFolderMissing, "base folder itself found");
}

static void TestValidatorExtras(const fs::path& temp) {
    // Weather.ini and language loose instead of inside archives.
    fs::path loose = temp / "Loose";
    for (const char* n : kZeroHourArchives) Archive(loose, n);
    for (const char* n : kBaseArchives) Archive(loose, n);
    CHECK(!Validate(loose.string()).ready(), "no weather / language anywhere");
    WriteFile(loose / "data" / "INI" / "DEFAULT" / "weather.INI", 10);
    Report r = Validate(loose.string());
    CHECK(r.weatherFound && !r.languageFound && !r.ready(), "loose weather only");
    WriteFile(loose / "Data" / "German" / "GENERALS.STR", 10);
    r = Validate(loose.string());
    CHECK(r.ready() && r.languages.size() == 1 && r.languages[0] == "German", "loose weather + loose .str, case-insensitive");
    // Empty (zero-byte) loose files never count.
    fs::path emptyLoose = temp / "EmptyLoose";
    for (const char* n : kZeroHourArchives) Archive(emptyLoose, n);
    for (const char* n : kBaseArchives) Archive(emptyLoose, n);
    WriteFile(emptyLoose / "Data" / "INI" / "Default" / "Weather.ini", 0);
    WriteFile(emptyLoose / "Data" / "English" / "generals.csf", 0);
    CHECK(!Validate(emptyLoose.string()).ready(), "zero-byte loose files do not satisfy weather/language");

    // Zero-size archive entries never satisfy weather/language.
    fs::path zeroEntry = temp / "ZeroEntry";
    for (const char* n : kZeroHourArchives) Archive(zeroEntry, n);
    for (const char* n : kBaseArchives) Archive(zeroEntry, n);
    WriteBig(zeroEntry / "Extra.big", {{"Data\\INI\\Default\\Weather.ini", 0}, {"Data\\English\\generals.csf", 0}});
    r = Validate(zeroEntry.string());
    CHECK(!r.weatherFound && !r.languageFound, "empty archive entries do not count");

    // Nested language folders and the [^/]+ rule: data//generals.csf and data/a/b/generals.csf do not count.
    fs::path badLang = temp / "BadLang";
    for (const char* n : kZeroHourArchives) Archive(badLang, n);
    for (const char* n : kBaseArchives) Archive(badLang, n, n == std::string("INI.big") ? "Data\\INI\\Default\\Weather.ini" : "s");
    WriteBig(badLang / "Lang.big", {{"Data\\a\\b\\generals.csf", 1}, {"Data\\generals.csf", 1}});
    CHECK(!Validate(badLang.string()).languageFound, "language entry must be exactly data/<lang>/generals.csf|str");

    // Depth bound: INIZH.big three folders down is not found; two folders down is.
    fs::path depth = temp / "Depth";
    MakeZh(depth / "a" / "b" / "c");
    MakeBase(depth / "a" / "b" / "c" / "ZH_Generals");
    r = Validate(depth.string());
    CHECK(r.zhChoices.empty() && r.verdict() == Verdict::NoZeroHour, "depth 3 is beyond the bounded search");
    CHECK(Validate((depth / "a").string()).ready(), "depth 2 is found");

    // Folder budget: 128 visited folders max (the root counts as one).
    fs::path budget = temp / "Budget";
    for (int i = 0; i < 140; i++) {
        char buf[16];
        std::snprintf(buf, sizeof(buf), "d%03d", i);
        fs::create_directories(budget / buf);
    }
    MakeZh(budget / "zzz");  // sorts after d000..d139
    CHECK(Validate(budget.string()).zhChoices.empty(), "folder budget stops the search at 128 folders");
    fs::path budgetOk = temp / "BudgetOk";
    for (int i = 0; i < 100; i++) {
        char buf[16];
        std::snprintf(buf, sizeof(buf), "d%03d", i);
        fs::create_directories(budgetOk / buf);
    }
    MakeZh(budgetOk / "zzz");
    CHECK(Validate(budgetOk.string()).zhChoices.size() == 1, "under the folder budget the folder is found");

    // Dot folders are skipped.
    fs::path hidden = temp / "Hidden";
    MakeZh(hidden / ".hidden");
    CHECK(Validate(hidden.string()).zhChoices.empty(), "dot folders are not searched");

    // Symlink loop terminates.
#if !defined(_WIN32)
    fs::path loop = temp / "Loop";
    fs::create_directories(loop / "sub");
    std::error_code ec;
    fs::create_directory_symlink(loop, loop / "sub" / "back", ec);
    CHECK(Validate(loop.string()).zhChoices.empty(), "symlink loop terminates");
#endif

    // Non-directory / missing selections.
    CHECK(Validate("").verdict() == Verdict::NoSelection, "empty selection");
    r = Validate((temp / "does-not-exist").string());
    CHECK(r.unreadable && r.verdict() == Verdict::Unreadable, "missing folder is unreadable");

    // Archive extras: complete vs minimal.
    fs::path complete = temp / "Complete";
    MakeZh(complete);
    MakeBase(complete / "ZH_Generals");
    r = Validate(complete.string());
    CHECK(r.ready() && !r.complete() && r.optionalMissing.size() == 2, "minimal set is ready but not complete");
    MakeExtras(complete);
    r = Validate(complete.string());
    CHECK(r.ready() && r.complete() && r.videosFound && r.voiceArchivesFound, "movies + voice archives -> complete");
    CHECK(r.summary().find("complete") != std::string::npos, "summary states completeness");

    // Summary lists missing files with reasons.
    fs::remove(complete / "W3DZH.big");
    r = Validate(complete.string());
    CHECK(r.summary().find("W3DZH.big") != std::string::npos, "summary names the missing file");
    CHECK(r.dump().find("missing=W3DZH.big") != std::string::npos, "dump names the missing file");

    // Oversized entry (>2 GiB) becomes a warning, not damage: build a header-only claim via a sparse-like
    // archive whose recorded size cannot fit the file, so use a legitimately large sparse file.
#if !defined(_WIN32)
    fs::path big = temp / "BigOffsets";
    for (const char* n : kZeroHourArchives) Archive(big, n);
    for (const char* n : kBaseArchives) Archive(big, n, n == std::string("INI.big") ? "Data\\INI\\Default\\Weather.ini" : "s");
    Archive(big, "EnglishZH.big", "Data\\English\\generals.csf");
    {
        // 16 header + one entry (offset/size/name) then a sparse 2.1 GB payload.
        uint32_t nameLen = 4;  // "big\0"
        uint32_t tableEnd = 16 + 8 + nameLen;
        uint32_t payload = 0x80000010u;
        std::string out = "BIGF";
        out.append(4, '\0');
        PutBE(out, 1);
        PutBE(out, tableEnd);
        PutBE(out, tableEnd);
        PutBE(out, payload);
        out += std::string("big") + '\0';
        std::ofstream f(big / "Huge.big", std::ios::binary | std::ios::trunc);
        f.write(out.data(), std::streamsize(out.size()));
        f.close();
        fs::resize_file(big / "Huge.big", tableEnd + uint64_t(payload));
    }
    r = Validate(big.string());
    bool hugeWarn = false;
    for (const auto& w : r.warnings) hugeWarn |= w.find("Huge.big") != std::string::npos && w.find("2 GiB") != std::string::npos;
    CHECK(r.ready() && hugeWarn, "entry beyond 2 GiB is a warning");
#endif
}

static void TestBigParsing(const fs::path& temp) {
    // Parsing parity with the engine's StdBIGFileSystem::openArchiveFile.
    fs::path dir = temp / "Parse";
    std::vector<Entry> entries = {{"Data\\INI\\Default\\Weather.ini", 7},
                                  {"Data/English/generals.csf", 300},
                                  {"art\\textures\\a.dds", 1},
                                  {"x", 0},
                                  {"Data\\Scripts\\Skirmish\\SkirmishScripts.scb", 4096}};
    WriteBig(dir / "A.big", entries);
    std::vector<BigEntry> mine;
    BigArchiveInfo info = ReadBigArchive((dir / "A.big").string(), [&](const BigEntry& e) { mine.push_back(e); });
    CHECK(info.ok && info.entryCount == entries.size(), "reader accepts a well-formed archive");
    std::vector<EngineEntry> engine;
    CHECK(EngineParse(dir / "A.big", engine), "engine reference parses the fixture");
    CHECK(engine.size() == mine.size(), "entry count equals the engine's");
    for (size_t i = 0; i < std::min(engine.size(), mine.size()); i++) {
        CHECK(engine[i].path == mine[i].path && uint32_t(engine[i].offset) == mine[i].offset &&
                  uint32_t(engine[i].size) == mine[i].size,
              "entry " + std::to_string(i) + " identical to the engine's parse");
    }
    // Big-endian on disk: count 5 -> 00 00 00 05 at offset 8.
    {
        std::ifstream f(dir / "A.big", std::ios::binary);
        char b[16];
        f.read(b, 16);
        CHECK(std::memcmp(b, "BIGF", 4) == 0 && b[8] == 0 && b[9] == 0 && b[10] == 0 && b[11] == 5,
              "count is big endian at offset 8");
    }
    // Fuzz: random valid archives parse identically.
    srand(12345);
    for (int iter = 0; iter < 200; iter++) {
        std::vector<Entry> es;
        int n = 1 + rand() % 40;
        for (int i = 0; i < n; i++) {
            std::string name;
            int parts = 1 + rand() % 4;
            for (int p = 0; p < parts; p++) {
                int len = 1 + rand() % 12;
                for (int c = 0; c < len; c++) name.push_back(char('a' + rand() % 26));
                if (p + 1 < parts) name.push_back(rand() % 2 ? '\\' : '/');
            }
            es.push_back({name, uint32_t(rand() % 50)});
        }
        WriteBig(dir / "F.big", es);
        std::vector<BigEntry> a;
        std::vector<EngineEntry> b;
        BigArchiveInfo i2 = ReadBigArchive((dir / "F.big").string(), [&](const BigEntry& e) { a.push_back(e); });
        bool okEngine = EngineParse(dir / "F.big", b);
        bool same = i2.ok && okEngine && a.size() == b.size();
        for (size_t i = 0; same && i < a.size(); i++) {
            same = a[i].path == b[i].path && a[i].offset == uint32_t(b[i].offset) && a[i].size == uint32_t(b[i].size);
        }
        CHECK(same, "fuzz archive " + std::to_string(iter) + " parses identically to the engine");
        if (!same) break;
    }

    // Rejections.
    WriteFile(dir / "Tiny.big", 10);
    CHECK(!ReadBigArchive((dir / "Tiny.big").string()).ok, "file shorter than a header rejected");
    {
        std::ofstream f(dir / "BadMagic.big", std::ios::binary);
        std::string s = "BIGX";
        s.append(64, '\0');
        f.write(s.data(), std::streamsize(s.size()));
    }
    BigArchiveInfo bad = ReadBigArchive((dir / "BadMagic.big").string());
    CHECK(!bad.ok && bad.error == "BIGF header", "bad magic rejected");
    WriteBig(dir / "Trunc.big", entries);
    fs::resize_file(dir / "Trunc.big", 30);
    CHECK(!ReadBigArchive((dir / "Trunc.big").string()).ok, "table cut short rejected");
    // Name that never terminates within the table.
    {
        std::string s = "BIGF";
        s.append(4, '\0');
        PutBE(s, 1);
        PutBE(s, 40);
        PutBE(s, 40);
        PutBE(s, 1);
        s.append(20, 'n');  // no NUL before tableEnd
        s.append(64, '\0');
        std::ofstream f(dir / "NoNul.big", std::ios::binary);
        f.write(s.data(), std::streamsize(s.size()));
    }
    CHECK(!ReadBigArchive((dir / "NoNul.big").string()).ok, "unterminated name rejected");
    // Payload overlapping the table (size > 0 && offset < tableEnd).
    {
        WriteBig(dir / "Overlap.big", {{"a", 5}});
        std::fstream f(dir / "Overlap.big", std::ios::in | std::ios::out | std::ios::binary);
        f.seekp(16);
        char off[4] = {0, 0, 0, 4};
        f.write(off, 4);
    }
    CHECK(!ReadBigArchive((dir / "Overlap.big").string()).ok, "payload overlapping the table rejected");
    // Overlong name (>= 511).
    {
        std::string longName(600, 'a');
        WriteBig(dir / "LongName.big", {{longName, 1}});
    }
    CHECK(!ReadBigArchive((dir / "LongName.big").string()).ok, "name of 511+ bytes rejected");
    CHECK(VerifyBigArchive((dir / "A.big").string(), fs::file_size(dir / "A.big")), "VerifyBigArchive ok");
    std::string why;
    CHECK(!VerifyBigArchive((dir / "A.big").string(), 5, &why) && why.find("size mismatch") != std::string::npos,
          "VerifyBigArchive size mismatch");
    CHECK(!ReadBigArchive((dir / "missing.big").string()).ok, "missing file rejected");
}

// ---- install --------------------------------------------------------------------------

struct Sources {
    fs::path steam;   // Zero Hour with nested ZH_Generals + extras + junk
    fs::path merged;  // one folder
};

static Sources MakeSources(const fs::path& temp, const char* tag) {
    Sources s;
    s.steam = temp / (std::string(tag) + "-steam") / "Zero Hour";
    MakeZh(s.steam);
    MakeBase(s.steam / "ZH_Generals");
    MakeExtras(s.steam);
    WriteFile(s.steam / "Data" / "English" / "Movies" / "outro.bik", 700000, 'w');
    WriteFile(s.steam / "generalszh.exe", 1000);
    WriteFile(s.steam / "binkw32.dll", 1000);
    WriteFile(s.steam / ".DS_Store", 10);
    WriteFile(s.steam / "readme.txt", 200, 't');
    WriteFile(s.steam / "ZH_Generals" / "Data" / "Scripts" / "MultiplayerScripts.scb", 1500, 'b');
#if !defined(_WIN32)
    std::error_code ec;
    fs::create_symlink(s.steam / "readme.txt", s.steam / "link.txt", ec);
#endif
    s.merged = temp / (std::string(tag) + "-merged");
    MakeZh(s.merged);
    MakeBase(s.merged);
    WriteFile(s.merged / "Data" / "Movies" / "m.bik", 100000, 'm');
    return s;
}

static Report MustBeReady(const fs::path& p, const fs::path& base = fs::path()) {
    Report r = Validate(p.string(), base.string());
    if (!r.ready()) std::fprintf(stderr, "fixture not ready:\n%s\n", r.summary().c_str());
    return r;
}

// Hooks that request cancellation once `afterFiles` source files have been opened for copying.
// (Progress callbacks are throttled to 10 Hz, which is far too coarse for tiny fixtures.)
static Hooks CancelAfterFiles(std::atomic<bool>& cancel, int afterFiles, std::shared_ptr<int> counter) {
    Hooks h;
    h.cancelled = [&cancel] { return cancel.load(); };
    h.readSource = [&cancel, afterFiles, counter](const std::string& src, const std::function<bool(const std::string&)>& body) {
        if (++*counter >= afterFiles) cancel = true;
        return body(src);
    };
    return h;
}

static void TestPlanAndSkips(const fs::path& temp) {
    CHECK(ShouldSkipEntry(".DS_Store", false) && ShouldSkipEntry(".git", true), "hidden entries skipped");
    CHECK(ShouldSkipEntry("Game.EXE", false) && ShouldSkipEntry("a.dll", false) && ShouldSkipEntry("d.cab", false) &&
              ShouldSkipEntry("x.iso", false) && ShouldSkipEntry("Thumbs.db", false),
          "executables, installers and OS junk skipped");
    CHECK(ShouldSkipEntry("__MACOSX", true) && ShouldSkipEntry("_CommonRedist", true), "junk folders skipped");
    CHECK(!ShouldSkipEntry("INIZH.big", false) && !ShouldSkipEntry("Data", true) && !ShouldSkipEntry("a.bik", false) &&
              !ShouldSkipEntry("generals.csf", false) && !ShouldSkipEntry("Options.ini", false),
          "game data is not skipped");

    Sources s = MakeSources(temp, "plan");
    Report r = MustBeReady(s.steam);
    InstallPlan plan;
    std::string err;
    CHECK(BuildInstallPlan(r, plan, &err), "plan builds");
    CHECK(plan.roles.size() == 2 && plan.roles[0].name == "ZH" && plan.roles[1].name == "Generals", "two roles for nested layout");
    bool nestedCopiedTwice = false, junk = false, has = false;
    for (const auto& f : plan.roles[0].files) {
        nestedCopiedTwice |= f.rel.rfind("ZH_Generals", 0) == 0;
        junk |= f.rel == "generalszh.exe" || f.rel == "binkw32.dll" || f.rel == ".DS_Store" || f.rel == "link.txt";
        has |= f.rel == "readme.txt";
    }
    CHECK(!nestedCopiedTwice, "nested ZH_Generals is not copied into the ZH role");
    CHECK(!junk && has, "junk and symlinks excluded, ordinary files included");
    bool scb = false;
    for (const auto& f : plan.roles[1].files) scb |= f.rel == "Data/Scripts/MultiplayerScripts.scb";
    CHECK(scb, "base role carries the nested tree (loose file included)");
    CHECK(plan.skippedEntries >= 4, "skipped entries counted");
    Report m = MustBeReady(s.merged);
    InstallPlan mp;
    CHECK(BuildInstallPlan(m, mp, &err) && mp.baseMerged && mp.roles.size() == 1, "merged layout has one role");
    Report bad = Validate((temp / "nope").string());
    CHECK(!BuildInstallPlan(bad, plan, &err), "plan refuses a source that failed validation");
}

static Hooks NoisyHooks(std::vector<Progress>* log) {
    Hooks h;
    h.progress = [log](const Progress& p) { log->push_back(p); };
    return h;
}

static void TestInstallBasics(const fs::path& temp) {
    Sources s = MakeSources(temp, "inst");
    fs::path gd = temp / "inst-gd" / "GameData";
    Report r = MustBeReady(s.steam);
    std::vector<Progress> log;
    std::vector<std::string> excluded;
    Hooks h = NoisyHooks(&log);
    h.excludeFromBackup = [&](const std::string& p) { excluded.push_back(p); };
    InstallResult res = Install(gd.string(), r, h);
    CHECK(res.ok(), "steam nested import succeeds: " + res.message);
    CHECK(res.filesCopied > 20 && res.bytesCopied > 3000000, "copy statistics");
    InstalledManifest m;
    CHECK(ReadInstalled(gd.string(), m), "manifest readable");
    CHECK(m.zhRoot == (gd / "ZH").string() && m.baseRoot == (gd / "Generals").string() && !m.baseMerged, "installed roots");
    CHECK(m.complete, "manifest records the complete data set");
    CHECK(m.languages == "English", "manifest records language");
    CHECK(!fs::exists(gd / "ZH" / "ZH_Generals"), "no duplicate nested base inside ZH");
    CHECK(fs::exists(gd / "Generals" / "Terrain.big"), "base archives at Generals/");
    CHECK(fs::exists(gd / "ZH" / "Data" / "Movies" / "intro.bik"), "loose movies copied");
    CHECK(!fs::exists(gd / "ZH" / "generalszh.exe") && !fs::exists(gd / "ZH" / ".DS_Store"), "junk not copied");
    CHECK(!fs::exists(gd / ".staging") && !fs::exists(gd / ".backup") && !fs::exists(gd / ".import-journal"), "no transaction leftovers");
    Report installed = Validate((gd / "ZH").string(), (gd / "Generals").string());
    CHECK(installed.ready() && installed.complete(), "installed tree validates (explicit base)");
    // Byte-for-byte equality of every copied file.
    bool identical = true;
    for (const auto& kv : TreeMap(gd / "ZH")) {
        fs::path src = s.steam / kv.first;
        if (!fs::exists(src) || fs::file_size(src) != kv.second) identical = false;
    }
    for (const auto& kv : TreeMap(gd / "Generals")) {
        fs::path src = s.steam / "ZH_Generals" / kv.first;
        if (!fs::exists(src) || fs::file_size(src) != kv.second) identical = false;
    }
    CHECK(identical, "every installed file matches its source size");
    {
        std::ifstream a(s.steam / "readme.txt", std::ios::binary), b(gd / "ZH" / "readme.txt", std::ios::binary);
        std::string sa((std::istreambuf_iterator<char>(a)), {}), sb((std::istreambuf_iterator<char>(b)), {});
        CHECK(sa == sb && !sa.empty(), "file content identical");
    }
    // Backup exclusion is requested for the root, staging and the final trees.
    bool rootEx = false, zhEx = false, baseEx = false;
    for (const auto& e : excluded) {
        rootEx |= e == gd.string();
        zhEx |= e == (gd / "ZH").string();
        baseEx |= e == (gd / "Generals").string();
    }
    CHECK(rootEx && zhEx && baseEx, "root and installed trees excluded from backup");
    // Progress is monotonic and finishes at 100 %.
    bool mono = true;
    uint64_t last = 0;
    for (const auto& p : log) {
        if (p.phase == Progress::Phase::Copying || p.phase == Progress::Phase::Verifying) {
            if (p.bytesDone < last) mono = false;
            last = p.bytesDone;
        }
    }
    CHECK(mono && !log.empty(), "progress bytes are monotonic");
    CHECK(log.back().phase == Progress::Phase::Done, "last progress phase is Done");
    CHECK(log.back().bytesDone == log.back().bytesTotal && log.back().filesDone == log.back().filesTotal, "progress reaches total");
    bool sawPhases[7] = {};
    for (const auto& p : log) sawPhases[int(p.phase)] = true;
    CHECK(sawPhases[0] && sawPhases[2] && sawPhases[3] && sawPhases[4] && sawPhases[6], "planning/copy/verify/commit/done phases reported");
    // Recover on a clean root does nothing.
    CHECK(Recover(gd.string()).action == RecoveryAction::None, "recover is a no-op after a clean import");

    // Merged import has a single tree, base == zh.
    fs::path gd2 = temp / "inst-gd2" / "GameData";
    Report rm = MustBeReady(s.merged);
    res = Install(gd2.string(), rm);
    CHECK(res.ok(), "merged import succeeds: " + res.message);
    CHECK(ReadInstalled(gd2.string(), m) && m.baseMerged && m.baseRoot == m.zhRoot, "merged manifest");
    CHECK(!fs::exists(gd2 / "Generals"), "merged import has no Generals tree");
    CHECK(Validate((gd2 / "ZH").string()).ready(), "merged install validates");

    // Re-import replaces a previous install completely (stale file gone, Generals role dropped).
    WriteFile(gd / "ZH" / "stale.txt", 10);
    res = Install(gd.string(), rm);
    CHECK(res.ok(), "re-import over an existing install: " + res.message);
    CHECK(ReadInstalled(gd.string(), m) && m.baseMerged, "layout switched to merged");
    CHECK(!fs::exists(gd / "ZH" / "stale.txt") && !fs::exists(gd / "Generals"), "old files and the obsolete Generals tree are gone");
    CHECK(!fs::exists(gd / ".backup"), "backup removed after success");

    // Invalid source.
    Report bad = Validate((temp / "nothing-here").string());
    res = Install((temp / "inst-gd3").string(), bad);
    CHECK(res.outcome == InstallOutcome::InvalidSource, "invalid source refused");
    CHECK(!fs::exists(temp / "inst-gd3" / "install.manifest"), "invalid source changes nothing");

    // RemoveInstalled.
    CHECK(RemoveInstalled(gd.string()) && !ReadInstalled(gd.string(), m) && !fs::exists(gd / "ZH"), "remove installed data");
}

static void TestResumeAndCancel(const fs::path& temp) {
    Sources s = MakeSources(temp, "res");
    Report r = MustBeReady(s.steam);
    fs::path gd = temp / "res-gd" / "GameData";
    // Cancel once ~half the bytes are copied.
    InstallPlan plan;
    std::string err;
    BuildInstallPlan(r, plan, &err);
    std::atomic<bool> cancel{false};
    Hooks h = CancelAfterFiles(cancel, int(plan.totalFiles / 2), std::make_shared<int>(0));
    InstallResult res = Install(gd.string(), r, h);
    CHECK(res.outcome == InstallOutcome::Cancelled && res.resumable, "cancel keeps a resumable partial import");
    InstalledManifest m;
    CHECK(!ReadInstalled(gd.string(), m), "cancelled import leaves no install");
    CHECK(fs::exists(gd / ".staging"), "partial copy kept");
    bool partLeft = false;
    {
        std::error_code lec;
        for (fs::recursive_directory_iterator it(gd / ".staging", lec), end; it != end && !lec; it.increment(lec))
            partLeft |= it->path().extension() == ".gxpart";
    }
    CHECK(!partLeft, "no half-written *.gxpart files survive a cancel");

    // "App restart": recovery reports a resumable import.
    RecoveryInfo rec = Recover(gd.string());
    CHECK(rec.action == RecoveryAction::PartialCopyKept, "recovery reports the partial import");
    CHECK(rec.sourceZh == r.zhRoot && rec.filesStaged > 0 && rec.bytesStaged > 0 && rec.bytesStaged < rec.bytesTotal,
          "recovery reports how much was copied");
    // Resume.
    std::vector<Progress> log;
    Hooks h2 = NoisyHooks(&log);
    res = Install(gd.string(), r, h2);
    CHECK(res.ok(), "resume completes: " + res.message);
    CHECK(res.filesReused > 0 && res.bytesReused > 0, "resume reuses the files that were already copied");
    CHECK(res.filesReused + res.filesCopied == plan.totalFiles, "reused + copied = all files");
    CHECK(res.bytesCopied < plan.totalBytes, "resume copies fewer bytes than a full import");
    CHECK(Validate((gd / "ZH").string(), (gd / "Generals").string()).ready(), "resumed install validates");
    CHECK(log.back().bytesReused > 0, "progress reports reused bytes");

    // Cancel at arbitrary poll counts (including in the middle of a multi-chunk file), then resume.
    int pollsChecked = 0;
    for (int polls = 1; polls <= 70; polls += 3) {
        fs::path gdp = temp / ("res-poll-" + std::to_string(polls)) / "GameData";
        auto counter = std::make_shared<int>(0);
        Hooks hp;
        hp.cancelled = [counter, polls] { return ++*counter >= polls; };
        InstallResult a = Install(gdp.string(), r, hp);
        if (a.outcome == InstallOutcome::Installed) continue;  // finished before the poll count was reached
        CHECK(a.outcome == InstallOutcome::Cancelled, "cancel at poll " + std::to_string(polls));
        if (!fs::exists(gdp / ".import-journal")) {
            CHECK(!a.resumable, "cancel while planning leaves nothing to resume (poll " + std::to_string(polls) + ")");
            continue;
        }
        pollsChecked++;
        CHECK(a.resumable, "cancel after copying started is resumable (poll " + std::to_string(polls) + ")");
        bool leftover = false;
        std::error_code lec;
        for (fs::recursive_directory_iterator it(gdp / ".staging", lec), end; it != end && !lec; it.increment(lec))
            leftover |= it->path().extension() == ".gxpart";
        CHECK(!leftover, "no *.gxpart after cancel at poll " + std::to_string(polls));
        InstallResult b = Install(gdp.string(), r);
        CHECK(b.ok() && Validate((gdp / "ZH").string(), (gdp / "Generals").string()).ready(),
              "resume after cancel at poll " + std::to_string(polls));
    }
    CHECK(pollsChecked >= 10, "arbitrary-point cancel matrix ran");

    // Interrupted import from a different source: partial data discarded, fresh import.
    fs::path gd2 = temp / "res-gd2" / "GameData";
    cancel = false;
    Hooks h3 = CancelAfterFiles(cancel, 5, std::make_shared<int>(0));
    res = Install(gd2.string(), r, h3);
    CHECK(res.outcome == InstallOutcome::Cancelled, "second cancel");
    Report other = MustBeReady(s.merged);
    res = Install(gd2.string(), other);
    CHECK(res.ok() && res.filesReused == 0, "different source never reuses foreign staged files");
    CHECK(ReadInstalled(gd2.string(), m) && m.baseMerged, "new source installed");

    // Discard.
    fs::path gd3 = temp / "res-gd3" / "GameData";
    cancel = false;
    h3 = CancelAfterFiles(cancel, 5, std::make_shared<int>(0));
    res = Install(gd3.string(), r, h3);
    CHECK(res.outcome == InstallOutcome::Cancelled, "third cancel");
    DiscardPartialImport(gd3.string());
    CHECK(!fs::exists(gd3 / ".staging") && !fs::exists(gd3 / ".import-journal"), "discard removes the partial import");
    CHECK(Recover(gd3.string()).action == RecoveryAction::None, "nothing to recover after discard");

    // Cancel while an older install exists: the older install stays intact.
    fs::path gd4 = temp / "res-gd4" / "GameData";
    CHECK(Install(gd4.string(), other).ok(), "install old (merged)");
    WriteFile(gd4 / "ZH" / "old-marker.txt", 7);
    cancel = false;
    h3 = CancelAfterFiles(cancel, 5, std::make_shared<int>(0));
    res = Install(gd4.string(), r, h3);
    CHECK(res.outcome == InstallOutcome::Cancelled, "cancel with an old install present");
    CHECK(ReadInstalled(gd4.string(), m) && fs::exists(gd4 / "ZH" / "old-marker.txt") && m.baseMerged,
          "old install intact after a cancelled re-import");
    CHECK(Validate((gd4 / "ZH").string()).ready(), "old install still validates");
}

static void TestFailures(const fs::path& temp) {
    Sources s = MakeSources(temp, "fail");
    Report r = MustBeReady(s.steam);

    // Not enough free space.
    fs::path gd = temp / "fail-gd" / "GameData";
    Hooks tight;
    tight.freeSpace = [](const std::string&, uint64_t* out) { *out = 10 * 1024 * 1024; return true; };
    InstallResult res = Install(gd.string(), r, tight);
    InstalledManifest m;
    CHECK(res.outcome == InstallOutcome::InsufficientSpace && res.bytesNeeded > res.bytesAvailable, "insufficient space is reported");
    CHECK(!ReadInstalled(gd.string(), m) && !fs::exists(gd / ".staging"), "no partial data when space check fails");
    CHECK(res.message.find("Not enough") != std::string::npos, "message is human readable");
    // Unknown free space proceeds.
    Hooks unknown;
    unknown.freeSpace = [](const std::string&, uint64_t*) { return false; };
    CHECK(Install(gd.string(), r, unknown).ok(), "unknown free space does not block the import");

    // Source changes while copying (short read).
    fs::path gd2 = temp / "fail-gd2" / "GameData";
    fs::path shortFile = temp / "fail-short.bin";
    Hooks changing;
    changing.readSource = [&](const std::string& src, const std::function<bool(const std::string&)>& body) {
        if (fs::path(src).filename() == "readme.txt") {
            WriteFile(shortFile, 5);
            return body(shortFile.string());
        }
        return body(src);
    };
    res = Install(gd2.string(), r, changing);
    CHECK(res.outcome == InstallOutcome::SourceChanged && res.resumable, "short read is a SourceChanged error");
    CHECK(!ReadInstalled(gd2.string(), m), "no install after a source change");
    // ...and resumes fine once the source is stable.
    res = Install(gd2.string(), r);
    CHECK(res.ok() && res.filesReused > 0, "import resumes after the source stabilises");

    // A copy whose archive is corrupted in transit fails the BIGF check.
    fs::path gd3 = temp / "fail-gd3" / "GameData";
    fs::path corrupt = temp / "fail-corrupt.big";
    Hooks flip;
    flip.readSource = [&](const std::string& src, const std::function<bool(const std::string&)>& body) {
        if (fs::path(src).filename() == "MapsZH.big") {
            fs::copy_file(src, corrupt, fs::copy_options::overwrite_existing);
            std::fstream f(corrupt, std::ios::in | std::ios::out | std::ios::binary);
            f.seekp(0);
            f.write("XXXX", 4);
            f.close();
            return body(corrupt.string());
        }
        return body(src);
    };
    res = Install(gd3.string(), r, flip);
    CHECK(res.outcome == InstallOutcome::VerificationFailed, "corrupted archive fails verification");
    CHECK(res.message.find("MapsZH.big") != std::string::npos, "message names the archive");
    CHECK(!ReadInstalled(gd3.string(), m), "no install after a failed verification");

    // Unreadable source file.
    fs::path gd4 = temp / "fail-gd4" / "GameData";
    Hooks noRead;
    noRead.readSource = [&](const std::string& src, const std::function<bool(const std::string&)>& body) {
        if (fs::path(src).filename() == "readme.txt") return body((temp / "fail-does-not-exist").string());
        return body(src);
    };
    res = Install(gd4.string(), r, noRead);
    CHECK(res.outcome == InstallOutcome::IoError, "unreadable source file is an I/O error");
    CHECK(!ReadInstalled(gd4.string(), m), "no install after an I/O error");
}

// Crash matrix: simulate dying at every step of the transaction, then recover.
static void TestCrashRecovery(const fs::path& temp) {
    Sources s = MakeSources(temp, "crash");
    Report nested = MustBeReady(s.steam);
    Report merged = MustBeReady(s.merged);
    InstallPlan plan;
    std::string err;
    BuildInstallPlan(nested, plan, &err);

    struct Crash { const char* step; int index; };
    std::vector<Crash> crashes;
    for (int i = 0; i < int(plan.totalFiles); i += 3) crashes.push_back({"copy-file", i});
    crashes.push_back({"copy-file", int(plan.totalFiles) - 1});
    crashes.push_back({"before-commit-journal", 0});
    crashes.push_back({"commit-backup", 0});
    crashes.push_back({"commit-backup", 1});
    crashes.push_back({"commit-move", 0});
    crashes.push_back({"commit-move", 1});
    crashes.push_back({"before-manifest", 0});
    crashes.push_back({"before-cleanup", 0});

    int scenarios = 0;
    for (int withOld = 0; withOld < 2; withOld++) {
        for (const auto& c : crashes) {
            scenarios++;
            fs::path gd = temp / ("crash-gd-" + std::to_string(scenarios)) / "GameData";
            if (withOld) {
                CHECK(Install(gd.string(), merged).ok(), "seed old install");
                WriteFile(gd / "ZH" / "old-marker.txt", 3);
            }
            Hooks h;
            h.crashAt = [&](const char* step, int idx) { return std::string(step) == c.step && idx == c.index; };
            InstallResult res = Install(gd.string(), nested, h);
            std::string tag = std::string(c.step) + "#" + std::to_string(c.index) + (withOld ? " (old)" : " (fresh)");
            CHECK(res.outcome == InstallOutcome::Aborted, "crash injected at " + tag);

            // "Relaunch": recover, then look at what the user has.
            RecoveryInfo rec = Recover(gd.string());
            InstalledManifest m;
            bool haveInstall = ReadInstalled(gd.string(), m);
            std::string step = c.step;
            bool commitPhase = step.rfind("commit", 0) == 0 || step == "before-manifest" || step == "before-cleanup";
            if (commitPhase) {
                CHECK(rec.action == RecoveryAction::RolledForward || rec.action == RecoveryAction::CleanedUp,
                      "commit-phase crash rolls forward at " + tag);
                CHECK(haveInstall && !m.baseMerged, "new install is in place after recovery at " + tag);
                Report v = Validate(m.zhRoot, m.baseRoot);
                CHECK(v.ready() && v.complete(), "recovered install validates at " + tag);
                CHECK(!fs::exists(gd / "ZH" / "old-marker.txt"), "old files are not mixed into the new install at " + tag);
                CHECK(!fs::exists(gd / ".staging") && !fs::exists(gd / ".backup") && !fs::exists(gd / ".import-journal"),
                      "no leftovers after recovery at " + tag);
                CHECK(Recover(gd.string()).action == RecoveryAction::None, "recovery is idempotent at " + tag);
            } else {
                // Copy phase: the previous install (if any) is untouched, the partial copy is resumable.
                if (withOld) {
                    CHECK(haveInstall && m.baseMerged && fs::exists(gd / "ZH" / "old-marker.txt"), "old install untouched at " + tag);
                } else {
                    CHECK(!haveInstall, "no install yet at " + tag);
                }
                if (step == "before-commit-journal") {
                    CHECK(rec.action == RecoveryAction::PartialCopyKept, "fully copied, uncommitted import is resumable at " + tag);
                } else {
                    CHECK(rec.action == RecoveryAction::PartialCopyKept, "partial import kept at " + tag);
                }
                // Finishing the import afterwards reuses the copied files and succeeds.
                InstallResult again = Install(gd.string(), nested);
                CHECK(again.ok(), "import completes after the crash at " + tag + ": " + again.message);
                CHECK(again.filesReused > 0, "completed import reuses copied files at " + tag);
                CHECK(ReadInstalled(gd.string(), m) && !m.baseMerged, "new install after finishing at " + tag);
                CHECK(Validate(m.zhRoot, m.baseRoot).ready(), "finished install validates at " + tag);
                CHECK(!fs::exists(gd / "ZH" / "old-marker.txt"), "old marker gone after replacing at " + tag);
            }
        }
    }
    CHECK(scenarios >= 30, "crash matrix has broad coverage");

    // A torn (unreadable) journal is discarded cleanly.
    fs::path gd = temp / "crash-torn" / "GameData";
    fs::create_directories(gd / ".staging" / "ZH");
    {
        std::ofstream j(gd / ".import-journal");
        j << "garb";
    }
    RecoveryInfo rec = Recover(gd.string());
    CHECK(rec.action == RecoveryAction::DiscardedUnusable && !fs::exists(gd / ".staging"), "torn journal is discarded");
    // Leftover staging without a journal is removed.
    fs::create_directories(gd / ".staging" / "ZH");
    CHECK(Recover(gd.string()).action == RecoveryAction::CleanedUp && !fs::exists(gd / ".staging"), "orphan staging removed");
    // A backup with no install and no manifest is restored.
    fs::create_directories(gd / ".backup" / "ZH");
    WriteFile(gd / ".backup" / "ZH" / "keep.txt", 4);
    Recover(gd.string());
    CHECK(fs::exists(gd / "ZH" / "keep.txt"), "orphan backup restored when the install went missing");
}

// ---------------------------------------------------------------------------------------

static int MakeFixtures(const fs::path& dir) {
    fs::remove_all(dir);
    // complete: Steam nested + extras
    MakeZh(dir / "complete" / "Steam" / "Zero Hour");
    MakeBase(dir / "complete" / "Steam" / "Zero Hour" / "ZH_Generals");
    MakeExtras(dir / "complete" / "Steam" / "Zero Hour");
    // minimal nested Steam (no movies/voices) at the root of its own folder
    MakeZh(dir / "nested" / "Zero Hour");
    MakeBase(dir / "nested" / "Zero Hour" / "ZH_Generals");
    // incomplete: missing MapsZH.big and base Audio.big
    MakeZh(dir / "incomplete" / "Zero Hour");
    MakeBase(dir / "incomplete" / "Zero Hour" / "ZH_Generals");
    fs::remove(dir / "incomplete" / "Zero Hour" / "MapsZH.big");
    fs::remove(dir / "incomplete" / "Zero Hour" / "ZH_Generals" / "Audio.big");
    // damaged: truncated archive
    MakeZh(dir / "damaged" / "Zero Hour");
    MakeBase(dir / "damaged" / "Zero Hour" / "ZH_Generals");
    fs::resize_file(dir / "damaged" / "Zero Hour" / "TerrainZH.big", fs::file_size(dir / "damaged" / "Zero Hour" / "TerrainZH.big") - 1);
    // installer only
    fs::create_directories(dir / "installer");
    std::ofstream(dir / "installer" / "data1.cab").put('x');
    std::ofstream(dir / "installer" / "setup.exe").put('x');
    // ambiguous
    MakeZh(dir / "ambiguous" / "One");
    MakeZh(dir / "ambiguous" / "Two");
    // merged single folder
    MakeZh(dir / "merged");
    MakeBase(dir / "merged");
    std::printf("fixtures written to %s\n", dir.string().c_str());
    return 0;
}

int main(int argc, char** argv) {
    if (argc >= 3 && std::string(argv[1]) == "--validate") {
        Report r = Validate(argv[2], argc > 3 ? argv[3] : "");
        std::printf("%s\n--- summary ---\n%s\n", r.dump().c_str(), r.summary().c_str());
        return r.ready() ? 0 : 1;
    }
    if (argc >= 3 && std::string(argv[1]) == "--make-fixtures") return MakeFixtures(argv[2]);

    fs::path temp = MakeTemp("suite");
    TestConstants();
    TestValidatorPortOfAndroidSuite(temp / "v");
    TestValidatorExtras(temp / "x");
    TestBigParsing(temp / "p");
    TestPlanAndSkips(temp / "plan");
    TestInstallBasics(temp / "i");
    TestResumeAndCancel(temp / "r");
    TestFailures(temp / "f");
    TestCrashRecovery(temp / "c");
    std::error_code ec;
    fs::remove_all(temp, ec);
    if (g_failures) {
        std::fprintf(stderr, "%d of %d checks FAILED\n", g_failures, g_checks);
        return 1;
    }
    std::printf("%d game-data checks passed\n", g_checks);
    return 0;
}
